services:
  # Laravel App
  app:
    image: laravelphp/php-fpm
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  postgres:
    image: postgres:13
    container_name: sakti_market
    environment:
      POSTGRES_USER: ifsakti
      POSTGRES_PASSWORD: root
      POSTGRES_DB: saktimarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  mysql_data:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
